CREATE DATABASE projeto;
USE projeto;

CREATE TABLE user(
cd INT AUTO_INCREMENT PRIMARY KEY,
nome VARCHAR(100) NOT NULL,
email VARCHAR(100) NOT NULL,
senha VARCHAR(20) NOT NULL,
foto VARCHAR(120) NULL);

CREATE TABLE categoria(
cd INT AUTO_INCREMENT PRIMARY KEY,
nome VARCHAR(200));